# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, groups, semigroupoids, semigroups }:

cabal.mkDerivation (self: {
  pname = "monoid-extras";
  version = "0.3.3.4";
  src = ./.;
  buildDepends = [ groups semigroupoids semigroups ];
  meta = {
    description = "Various extra monoid-related definitions and utilities";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
