# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, colour }:

cabal.mkDerivation (self: {
  pname = "palette";
  version = "0.1.0.1";
  src = ./.;
  buildDepends = [ colour ];
  meta = {
    homepage = "http://projects.haskell.org/diagrams";
    description = "Utilities for choosing and creating color schemes";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
