# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, attoparsec, blazeMarkup, blazeSvg, dataDefaultClass
, diagramsCore, diagramsLib, parsec, split, text, tuple, vector
, xml
}:

cabal.mkDerivation (self: {
  pname = "SVGFonts";
  version = "1.4.0.3";
  src = ./.;
  buildDepends = [
    attoparsec blazeMarkup blazeSvg dataDefaultClass diagramsCore
    diagramsLib parsec split text tuple vector xml
  ];
  meta = {
    description = "Fonts from the SVG-Font format";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
