# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, blazeHtml, cmdargs, ghcPaths, highlightingKate, hxt, split
}:

cabal.mkDerivation (self: {
  pname = "docutils";
  version = "0.1";
  src = ./.;
  buildDepends = [
    blazeHtml cmdargs ghcPaths highlightingKate hxt split
  ];
  meta = {
    description = "Transformers and writers for docutils XML";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
