# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, diagramsBuilder, diagramsCairo, diagramsLib, filepath
, linear, pandocTypes
}:

cabal.mkDerivation (self: {
  pname = "diagrams-pandoc";
  version = "0.1";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    diagramsBuilder diagramsCairo diagramsLib filepath linear
    pandocTypes
  ];
  meta = {
    description = "A pandoc filter to express diagrams inline using the haskell EDSL _diagrams_";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
