# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dataDefaultClass, lens, linear }:

cabal.mkDerivation (self: {
  pname = "force-layout";
  version = "0.3.0.7";
  src = ./.;
  buildDepends = [ dataDefaultClass lens linear ];
  meta = {
    description = "Simple force-directed layout";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
