# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, ansiTerminal, base64Bytestring, blazeSvg, Cabal
, cautiousFile, cmdargs, cpphs, diagramsBuilder, diagramsLib
, diagramsSvg, filepath, haskellSrcExts, lens, mtl, parsec
, QuickCheck, split, strict, tasty, tastyQuickcheck, text, uniplate
, vectorSpace
}:

cabal.mkDerivation (self: {
  pname = "diagrams-haddock";
  version = "0.2.2.12";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    ansiTerminal base64Bytestring blazeSvg Cabal cautiousFile cmdargs
    cpphs diagramsBuilder diagramsLib diagramsSvg filepath
    haskellSrcExts lens mtl parsec split strict text uniplate
    vectorSpace
  ];
  testDepends = [
    haskellSrcExts lens parsec QuickCheck tasty tastyQuickcheck
  ];
  meta = {
    homepage = "http://projects.haskell.org/diagrams/";
    description = "Preprocessor for embedding diagrams in Haddock documentation";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
