# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, base64Bytestring, blazeMarkup, blazeSvg, colour
, diagramsCore, diagramsLib, filepath, hashable, JuicyPixels, lens
, monoidExtras, mtl, optparseApplicative, split, time, vectorSpace
}:

cabal.mkDerivation (self: {
  pname = "diagrams-svg";
  version = "1.1";
  src = ./.;
  buildDepends = [
    base64Bytestring blazeMarkup blazeSvg colour diagramsCore
    diagramsLib filepath hashable JuicyPixels lens monoidExtras mtl
    optparseApplicative split time vectorSpace
  ];
  meta = {
    homepage = "http://projects.haskell.org/diagrams/";
    description = "SVG backend for diagrams drawing EDSL";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
