# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cmdargs, diagramsLib, exceptions, filepath, hashable ,
haskellSrcExts, hint, lens, mtl, split, transformers, diagramsCairo,
diagramsPostscript, diagramsSvg, blazeSvg
}:

cabal.mkDerivation (self: {
  pname = "diagrams-builder";
  version = "0.6.0.1";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    cmdargs diagramsLib exceptions filepath hashable haskellSrcExts
    hint lens mtl split transformers diagramsCairo diagramsPostscript
    diagramsSvg blazeSvg
      ];
  meta = {
    homepage = "http://projects.haskell.org/diagrams";
    description = "hint-based build service for the diagrams graphics EDSL";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
