# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, adjunctions, distributive, dualTree, lens, linear
, monoidExtras, mtl, semigroups, unorderedContainers
}:

cabal.mkDerivation (self: {
  pname = "diagrams-core";
  version = "1.2";
  src = ./.;
  buildDepends = [
    adjunctions distributive dualTree lens linear monoidExtras mtl
    semigroups unorderedContainers
  ];
  meta = {
    homepage = "http://projects.haskell.org/diagrams";
    description = "Core libraries for diagrams EDSL";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
