# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, Cabal, regexBase, regexPcre, shelly, systemFilepath, text
}:

cabal.mkDerivation (self: {
  pname = "release";
  version = "0.1";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    Cabal regexBase regexPcre shelly systemFilepath text
  ];
  meta = {
    homepage = "http://github.com/bergey/diagrams-stow";
    description = "Automate point releases and other tasks for Diagrams, and other Haskell packages with similar conventions";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
