# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, active, colour, dataDefaultClass, diagramsCore, dualTree
, filepath, fingertree, fsnotify, hashable, intervals, JuicyPixels
, lens, MemoTrie, monoidExtras, optparseApplicative, safe
, semigroups, systemFilepath, tagged, text, vectorSpace
, vectorSpacePoints
}:

cabal.mkDerivation (self: {
  pname = "diagrams-lib";
  version = "1.2";
  src = ./.;
  buildDepends = [
    active colour dataDefaultClass diagramsCore dualTree filepath
    fingertree fsnotify hashable intervals JuicyPixels lens MemoTrie
    monoidExtras optparseApplicative safe semigroups systemFilepath
    tagged text vectorSpace vectorSpacePoints
  ];
  meta = {
    homepage = "http://projects.haskell.org/diagrams";
    description = "Embedded domain-specific language for declarative graphics";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
