# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cairo, colour, dataDefaultClass, diagramsCore, diagramsLib
, filepath, hashable, JuicyPixels, lens, mtl, optparseApplicative
, pango, split, statestack, transformers, vector
}:

cabal.mkDerivation (self: {
  pname = "diagrams-cairo";
  version = "1.2";
  src = ./.;
  buildDepends = [
    cairo colour dataDefaultClass diagramsCore diagramsLib filepath
    hashable JuicyPixels lens mtl optparseApplicative pango split
    statestack transformers vector
  ];
  meta = {
    homepage = "http://projects.haskell.org/diagrams";
    description = "Cairo backend for diagrams drawing EDSL";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
