# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, lens, linear, QuickCheck, semigroupoids, semigroups
, vector
}:

cabal.mkDerivation (self: {
  pname = "active";
  version = "0.1.0.16";
  src = ./.;
  buildDepends = [ lens linear semigroupoids semigroups vector ];
  testDepends = [
    lens linear QuickCheck semigroupoids semigroups vector
  ];
  meta = {
    description = "Abstractions for animation";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
