# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, blankCanvas, cmdargs, dataDefaultClass, diagramsCore
, diagramsLib, lens, mtl, NumInstances, optparseApplicative
, statestack, text, vectorSpace
}:

cabal.mkDerivation (self: {
  pname = "diagrams-canvas";
  version = "0.3.0.2";
  src = ./.;
  buildDepends = [
    blankCanvas cmdargs dataDefaultClass diagramsCore diagramsLib lens
    mtl NumInstances optparseApplicative statestack text vectorSpace
  ];
  meta = {
    homepage = "http://projects.haskell.org/diagrams/";
    description = "HTML5 canvas backend for diagrams drawing EDSL";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
