# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, colour, concurrentSupply, diagramsCore, diagramsLib, lens
, linear, mtl
}:

cabal.mkDerivation (self: {
  pname = "diagrams-povray";
  version = "0.1";
  src = ./.;
  buildDepends = [
    colour concurrentSupply diagramsCore diagramsLib lens linear mtl
  ];
  meta = {
    homepage = "http://projects.haskell.org/diagrams";
    description = "Persistence Of Vision raytracer backend for diagrams EDSL";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
