# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dataDefaultClass, diagramsCore, diagramsLib, filepath
, FontyFruity, JuicyPixels, lens, mtl, optparseApplicative
, Rasterific, split, statestack
}:

cabal.mkDerivation (self: {
  pname = "diagrams-rasterific";
  version = "0.1";
  src = ./.;
  buildDepends = [
    dataDefaultClass diagramsCore diagramsLib filepath FontyFruity
    JuicyPixels lens mtl optparseApplicative Rasterific split
    statestack
  ];
  meta = {
    homepage = "http://projects.haskell.org/diagrams/";
    description = "Rasterific backend for diagrams";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
