# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, blazeBuilder, colour, dataDefault, diagramsCore
, diagramsLib, filepath, hashable, lens, mtl, optparseApplicative
, random, split, texrunner, time, vectorSpace
}:

cabal.mkDerivation (self: {
  pname = "diagrams-pgf";
  version = "0.1";
  src = ./.;
  buildDepends = [
    blazeBuilder colour dataDefault diagramsCore diagramsLib filepath
    hashable lens mtl optparseApplicative random split texrunner time
    vectorSpace
  ];
  meta = {
    homepage = "http://github.com/cchalmers/diagrams-pgf";
    description = "PGF backend for diagrams drawing EDSL";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
